# Seed data matching frontend mock.js

PERSONAL_INFO = {
    "name": "Ajibola Akelebe",
    "tagline": "Design & Engineering,",
    "tagline_suffix": "No boundaries.",
    "description": "Developer and designer based in Nigeria, building for a global audience. I teach what I know and ship what I learn.",
    "role": "// FULL-STACK \u00b7 UI DESIGN \u00b7 EDUCATOR \u00b7 CREATOR",
    "email": "hello@ajibolagenius.com",
    "location": "Lagos, Nigeria",
    "availability": "Available for projects",
    "social": {
        "github": "https://github.com/ajibolagenius",
        "twitter": "https://twitter.com/ajibolagenius",
        "linkedin": "https://linkedin.com/in/ajibolagenius",
        "whatsapp": "https://wa.me/2348000000000",
    },
}

PROJECTS = [
    {
        "slug": "rant",
        "name": "Rant \u2014 Anonymous Expression",
        "category": "Platform \u00b7 Social",
        "label": "RANT",
        "description": "A modern, anonymous social platform where users express freely in a safe environment.",
        "tags": ["Next.js", "Supabase", "Tailwind"],
        "type": "dev",
        "featured": True,
        "live_url": "#",
        "github_url": "#",
        "problem": "People need a safe space to express frustration, share controversial opinions, and vent without the social consequences of being identified. Existing platforms tie every post to an identity, creating self-censorship.",
        "solution": "Rant provides a fully anonymous social experience where users can post, react, and engage without accounts. The platform uses content moderation AI to keep things safe while maintaining anonymity. A unique 'heat map' shows trending topics across Nigerian cities.",
        "role_title": "Lead Developer & Designer",
        "duration": "3 months",
        "year": "2023",
        "tech_details": [
            {
                "name": "Next.js 14",
                "role": "Framework \u2014 App Router, RSC, API routes",
            },
            {
                "name": "Supabase",
                "role": "Backend \u2014 Auth, Realtime DB, Edge Functions",
            },
            {
                "name": "Tailwind CSS",
                "role": "Styling \u2014 Utility-first, custom design tokens",
            },
            {"name": "Vercel", "role": "Deployment \u2014 Edge functions, analytics"},
        ],
    },
    {
        "slug": "narvo",
        "name": "Narvo \u2014 News that Speaks",
        "category": "Mobile \u00b7 Voice \u00b7 News",
        "label": "NARVO",
        "description": "Voice-first news platform aggregating and reading global news in localised Nigerian voices.",
        "tags": ["React Native", "TTS API"],
        "type": "dev",
        "featured": True,
        "live_url": "#",
        "github_url": "#",
        "problem": "Many Nigerians consume news on the go. Reading articles on small screens is inconvenient. Existing TTS solutions sound robotic and use Western accents.",
        "solution": "Narvo aggregates news from trusted sources, then reads them aloud using custom TTS voices trained on Nigerian English accents. Users can create playlists, bookmark stories, and listen offline.",
        "role_title": "Full-Stack Developer",
        "duration": "4 months",
        "year": "2023",
        "tech_details": [
            {
                "name": "React Native",
                "role": "Mobile \u2014 Cross-platform iOS & Android",
            },
            {"name": "TTS API", "role": "Voice \u2014 Custom Nigerian accent models"},
            {"name": "Node.js", "role": "Backend \u2014 News aggregation & caching"},
            {"name": "MongoDB", "role": "Database \u2014 User preferences, bookmarks"},
        ],
    },
    {
        "slug": "corpssmart",
        "name": "CorpsMart \u2014 NYSC Made Easy",
        "category": "Web App \u00b7 Utility",
        "label": "CORPSSMART",
        "description": "A comprehensive toolkit for Nigerian corps members \u2014 PPA finder, marketplace, and community hub.",
        "tags": ["React", "Node.js", "MongoDB"],
        "type": "dev",
        "featured": True,
        "live_url": "#",
        "github_url": "#",
        "problem": "NYSC corps members face a disorganized service year \u2014 finding a PPA, buying/selling camp items, and connecting with batch mates is fragmented across WhatsApp groups.",
        "solution": "CorpsMart centralises everything: a PPA directory with reviews, a marketplace for camp supplies, batch community forums, and an interactive map of orientation camps.",
        "role_title": "Lead Developer",
        "duration": "5 months",
        "year": "2023",
        "tech_details": [
            {"name": "React", "role": "Frontend \u2014 SPA with dynamic routing"},
            {"name": "Node.js", "role": "Backend \u2014 REST API, authentication"},
            {"name": "MongoDB", "role": "Database \u2014 Users, listings, reviews"},
            {"name": "Cloudinary", "role": "Media \u2014 Image uploads & optimization"},
        ],
    },
    {
        "slug": "portfolio-ds",
        "name": "Portfolio Design System",
        "category": "Design \u00b7 System",
        "label": "DESIGN SYSTEM",
        "description": "A comprehensive design system fusing Afrofuturism with dark cosmic aesthetics for personal branding.",
        "tags": ["Figma", "CSS", "Design Tokens"],
        "type": "design",
        "featured": False,
        "live_url": "#",
        "github_url": "#",
        "problem": "Personal branding in tech often defaults to generic templates that fail to convey cultural identity.",
        "solution": "Created a complete design system with 8 chapters covering colour, typography, spacing, components, motion, and architecture.",
        "role_title": "Designer",
        "duration": "2 months",
        "year": "2024",
        "tech_details": [
            {
                "name": "Figma",
                "role": "Design \u2014 Components, auto-layout, variants",
            },
            {
                "name": "CSS Variables",
                "role": "Tokens \u2014 Colors, spacing, typography",
            },
            {"name": "HTML/CSS", "role": "Documentation \u2014 Living style guide"},
        ],
    },
    {
        "slug": "adire-visuals",
        "name": "Adire Visual Identity",
        "category": "3D \u00b7 Branding",
        "label": "ADIRE",
        "description": "Three.js powered generative art exploring Adire textile patterns as interactive 3D geometry.",
        "tags": ["Three.js", "GLSL", "WebGL"],
        "type": "design",
        "featured": False,
        "live_url": "#",
        "github_url": "#",
        "problem": "Traditional Adire textile patterns are 2D and static. I wanted to explore how these patterns could live in 3D space.",
        "solution": "Built a generative art system using Three.js and custom GLSL shaders that maps Adire patterns onto 3D geometries.",
        "role_title": "Creative Developer",
        "duration": "1 month",
        "year": "2024",
        "tech_details": [
            {"name": "Three.js", "role": "3D \u2014 Scene, camera, renderer"},
            {"name": "GLSL", "role": "Shaders \u2014 Custom pattern generation"},
            {"name": "WebGL", "role": "Rendering \u2014 GPU-accelerated graphics"},
            {"name": "dat.GUI", "role": "Controls \u2014 Real-time parameter tweaking"},
        ],
    },
]

COURSES = [
    {
        "slug": "fullstack",
        "name": "Full-Stack Web Development",
        "duration": "10 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6350K",
        "badge": "Full-Stack",
        "description": "Master frontend, backend, databases, and deployment from scratch. Build 5 real projects.",
        "curriculum": [
            "HTML/CSS/JS Fundamentals",
            "React & Component Architecture",
            "Node.js & Express APIs",
            "MongoDB & Database Design",
            "Authentication & Security",
            "Deployment & DevOps",
        ],
    },
    {
        "slug": "ui-design",
        "name": "UI Design & Prototyping",
        "duration": "4 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6200K",
        "badge": "Design",
        "description": "Learn design thinking, Figma mastery, and prototyping workflows.",
        "curriculum": [
            "Design Principles & Theory",
            "Figma Deep Dive",
            "Component Systems",
            "Prototyping & Handoff",
        ],
    },
    {
        "slug": "react",
        "name": "React & Next.js Mastery",
        "duration": "8 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6300K",
        "badge": "Frontend",
        "description": "Deep dive into React, Next.js, state management, and performance.",
        "curriculum": [
            "React Fundamentals",
            "Hooks & State Management",
            "Next.js App Router",
            "Server Components",
            "API Routes & Data Fetching",
            "Performance Optimization",
        ],
    },
    {
        "slug": "python",
        "name": "Python for Beginners",
        "duration": "6 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6180K",
        "badge": "Backend",
        "description": "Start your coding journey with Python fundamentals and real projects.",
        "curriculum": [
            "Python Basics & Syntax",
            "Data Structures",
            "Functions & OOP",
            "File Handling",
            "Web Scraping",
            "Final Project",
        ],
    },
    {
        "slug": "mobile",
        "name": "React Native Mobile Dev",
        "duration": "8 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6320K",
        "badge": "Mobile",
        "description": "Build cross-platform mobile applications with React Native.",
        "curriculum": [
            "React Native Setup",
            "Core Components",
            "Navigation",
            "State & APIs",
            "Native Modules",
            "App Store Deployment",
        ],
    },
    {
        "slug": "threejs",
        "name": "Creative Coding with Three.js",
        "duration": "6 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6280K",
        "badge": "3D",
        "description": "Learn WebGL, shaders, and 3D web experiences with Three.js.",
        "curriculum": [
            "3D Fundamentals",
            "Three.js Basics",
            "Geometries & Materials",
            "Lighting & Shadows",
            "Custom Shaders",
            "Portfolio Piece",
        ],
    },
    {
        "slug": "javascript",
        "name": "JavaScript Deep Dive",
        "duration": "6 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6220K",
        "badge": "Core",
        "description": "Master JavaScript from closures to async patterns and ES6+ features.",
        "curriculum": [
            "JS Engine & Execution Context",
            "Closures & Scope",
            "Prototypes & Classes",
            "Async Patterns",
            "DOM Manipulation",
            "Modern ES6+",
        ],
    },
    {
        "slug": "tailwind",
        "name": "Tailwind CSS Masterclass",
        "duration": "3 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6120K",
        "badge": "CSS",
        "description": "Build beautiful, responsive interfaces at speed with Tailwind CSS.",
        "curriculum": [
            "Utility-First Approach",
            "Responsive Design",
            "Custom Configuration",
            "Component Patterns",
        ],
    },
    {
        "slug": "git",
        "name": "Git & GitHub for Teams",
        "duration": "2 Weeks \u00b7 Remote \u00b7 Anytime",
        "price": "\u20a6100K",
        "badge": "DevOps",
        "description": "Version control, branching strategies, and collaborative workflows.",
        "curriculum": [
            "Git Fundamentals",
            "Branching & Merging",
            "GitHub Workflows",
            "CI/CD Basics",
        ],
    },
]

BLOG_POSTS = [
    {
        "slug": "afrofuturism-web-design",
        "title": "Afrofuturism in Web Design: Building Digital Identity",
        "date": "2024-12-15",
        "tags": ["Design", "Culture", "Identity"],
        "category": "Design",
        "excerpt": "How African geometric heritage can shape the future of web design \u2014 from Kente grids to cosmic interfaces.",
        "body": "The web design landscape has long been dominated by Western aesthetic conventions. Clean, minimal, Helvetica-driven. But what if we designed from a different starting point? What if the grid system was inspired by Kente cloth, and the color palette drew from terracotta and gold rather than corporate blue?\n\nThis is the thesis behind my portfolio's design system \u2014 a fusion of Afrofuturism and dark cosmic aesthetics that I call 'Cultural-First Design'. The idea is simple: every layout decision should trace back to a cultural or personal reference.\n\nThe grid is a Kente pattern. The orb is a star. The dividers carry the visual language of Adire textiles. These aren't decorative choices \u2014 they're identity statements.\n\nWhen I started building this system, I asked myself: can a portfolio website be unmistakably Nigerian without relying on clich\u00e9s? No Ankara backgrounds, no green-white-green flags. Instead, I reached for the geometric precision of traditional textile patterns and mapped them onto modern CSS grid systems.\n\nThe result is a design language that feels both rooted and futuristic \u2014 African heritage meeting cosmic depth.",
        "read_time": "5 min",
    },
    {
        "slug": "teaching-code-nigeria",
        "title": "Why I Teach Code in Nigeria (And What I've Learned)",
        "date": "2024-11-20",
        "tags": ["Education", "Nigeria", "Career"],
        "category": "Education",
        "excerpt": "Reflections on teaching 200+ students remotely across Nigeria \u2014 the challenges, the breakthroughs, and why it matters.",
        "body": "Teaching wasn't the plan. I was building products, freelancing, shipping code. But when a friend asked me to explain React hooks to their team, something clicked.\n\nThe Nigerian tech ecosystem is booming, but there's a massive gap between ambition and access. Thousands of aspiring individuals have the hunger but lack structured mentorship. Bootcamps are expensive. YouTube tutorials lack accountability.\n\nSo I started teaching \u2014 first informally, then structured into courses. 9 courses later, with 200+ students across multiple states, here's what I've learned:\n\n1. Start with 'why', not 'what'. Students who understand the problem before the solution retain 3x more.\n2. Projects beat theory every time. My students ship real apps from week 2.\n3. Community is everything. The WhatsApp groups outlast the courses.\n4. Pricing must be accessible. My courses are priced for Nigerian reality, not Silicon Valley budgets.\n\nTeaching has made me a better developer. Explaining concepts forces you to truly understand them.",
        "read_time": "4 min",
    },
    {
        "slug": "threejs-african-patterns",
        "title": "Mapping Adire Patterns to 3D Geometry with Three.js",
        "date": "2024-10-08",
        "tags": ["Three.js", "Creative Coding", "Tutorial"],
        "category": "Technical",
        "excerpt": "A technical deep-dive into creating generative Adire textile patterns using custom GLSL shaders and Three.js.",
        "body": "Adire is a traditional Yoruba textile art that uses resist-dyeing techniques to create intricate geometric patterns. These patterns have a mathematical beauty that maps perfectly to shader programming.\n\nThe core idea: use mathematical functions (sin, cos, step, smoothstep) to recreate the geometric vocabulary of Adire patterns, then map them onto 3D geometry.\n\nStep 1: Analyze the patterns. Traditional Adire uses repetition, symmetry, and geometric primitives.\n\nStep 2: Translate to math. Each motif becomes a GLSL function. Circles become distance fields. Lines become step functions.\n\nStep 3: Map to geometry. Using UV coordinates on a sphere, the 2D patterns wrap around 3D surfaces, creating an otherworldly effect.",
        "read_time": "8 min",
    },
    {
        "slug": "building-rant-app",
        "title": "Building Rant: Lessons from an Anonymous Social Platform",
        "date": "2024-09-15",
        "tags": ["Case Study", "Next.js", "Product"],
        "category": "Technical",
        "excerpt": "The technical and product decisions behind Rant \u2014 from real-time updates to content moderation at scale.",
        "body": "Rant started as a weekend project and grew into a platform with thousands of daily posts. Here's the story of how it was built.\n\nThe core challenge: how do you build a social platform that's anonymous yet safe? Full anonymity attracts toxicity. Full moderation kills freedom. The answer was a layered approach.\n\nLayer 1: AI content moderation using Perspective API. Every post is scored before publishing.\n\nLayer 2: Community reporting. Users can flag posts, and a threshold triggers review.\n\nLayer 3: Rate limiting. IP-based rate limiting prevents spam without compromising anonymity.\n\nThe tech stack \u2014 Next.js 14, Supabase, and Tailwind \u2014 was chosen for developer experience.",
        "read_time": "6 min",
    },
    {
        "slug": "design-system-from-scratch",
        "title": "Creating a Design System from Scratch: My Process",
        "date": "2024-08-01",
        "tags": ["Design", "Process", "Tutorial"],
        "category": "Design",
        "excerpt": "A behind-the-scenes look at building a comprehensive design system \u2014 from concept to tokens to components.",
        "body": "A design system isn't a Figma file. It's a language. Here's how I built mine from scratch.\n\nPhase 1: Concept. Before touching any tool, I defined two identity pillars: African geometric heritage (Afro Warm) and cosmic depth (Cosmic Cool).\n\nPhase 2: Tokens. Colors, typography, spacing, border radius \u2014 all defined as variables. I use a base-4 spacing scale.\n\nPhase 3: Components. Buttons, cards, badges, inputs, timeline \u2014 each carries the design language consistently.\n\nPhase 4: Documentation. A living HTML document that serves as both reference and proof of concept.",
        "read_time": "7 min",
    },
]

GALLERY_ITEMS = [
    {"title": "Rant UI \u2014 Feed View", "type": "UI", "color": "#E8A020"},
    {"title": "Adire Pattern \u2014 Sphere", "type": "3D", "color": "#5B4FD8"},
    {"title": "CorpsMart \u2014 Dashboard", "type": "UI", "color": "#1CB8D4"},
    {"title": "Narvo \u2014 Player Screen", "type": "UI", "color": "#C94B2D"},
    {"title": "Kente Grid System", "type": "Graphic", "color": "#E8A020"},
    {"title": "Cosmic Orb \u2014 Hero Scene", "type": "3D", "color": "#8B72F0"},
    {
        "title": "Design Tokens \u2014 Color Palette",
        "type": "Graphic",
        "color": "#A0622A",
    },
    {"title": "Portfolio \u2014 Mobile Responsive", "type": "UI", "color": "#1CB8D4"},
    {"title": "Adire Pattern \u2014 Flat", "type": "Graphic", "color": "#D63B1F"},
    {"title": "Three.js Particle System", "type": "3D", "color": "#5B4FD8"},
    {"title": "Rant \u2014 Dark Mode Cards", "type": "UI", "color": "#E8A020"},
    {"title": "Generative Art \u2014 Experiment", "type": "3D", "color": "#8B72F0"},
]

TIMELINE_ENTRIES = [
    {
        "year": "2024 \u2014 Present",
        "title": "Lead Developer & Designer",
        "body": "Building full-stack products and teaching 9 programming courses remotely across Nigeria and beyond.",
        "accent": "sungold",
        "order": 0,
    },
    {
        "year": "2023",
        "title": "Shipped: CorpsMart, Narvo, Rant",
        "body": "Three production-grade applications solving real problems in the Nigerian market.",
        "accent": "nebula",
        "order": 1,
    },
    {
        "year": "2022",
        "title": "Started Teaching & Freelancing",
        "body": "Began remote teaching career while taking on freelance web development and design projects.",
        "accent": "stardust",
        "order": 2,
    },
    {
        "year": "2021",
        "title": "Deep Dive into Full-Stack",
        "body": "Focused on mastering React, Node.js, and modern web development frameworks.",
        "accent": "terracotta",
        "order": 3,
    },
]

TESTIMONIALS = [
    {
        "name": "Adebayo Ogunlesi",
        "role": "Student \u2014 Full-Stack Course",
        "text": "Ajibola's teaching style is unlike anything I've experienced. He breaks down complex concepts into digestible pieces. I went from zero to deploying my first app in 8 weeks.",
    },
    {
        "name": "Chioma Nwosu",
        "role": "Client \u2014 Web Development",
        "text": "Working with Ajibola was transformative. He didn't just build a website; he crafted an experience that perfectly captured our brand identity.",
    },
    {
        "name": "Tunde Bakare",
        "role": "Student \u2014 React Course",
        "text": "The best investment I made in my career. Ajibola's mentorship and hands-on approach made learning React genuinely enjoyable and practical.",
    },
    {
        "name": "Folake Adeyemi",
        "role": "Student \u2014 UI Design Course",
        "text": "Before this course, I had no design background. Now I'm confidently creating interfaces in Figma and landing freelance design gigs.",
    },
    {
        "name": "Emeka Obi",
        "role": "Client \u2014 Mobile App",
        "text": "Ajibola delivered a polished React Native app ahead of schedule. His attention to detail and understanding of user experience is exceptional.",
    },
]
