-- Insert Vertex side project entry into public.projects
--
-- Vertex was built as a watch-and-build-along of a JavaScript Mastery tutorial.
-- The projects table has no dedicated credit column, so the attribution (video
-- title, channel, URL) lives in `solution`, `description` and the `type` field,
-- which the detail page already renders.
insert into public.projects (
  slug,
  name,
  category,
  label,
  description,
  kind,
  status,
  tags,
  type,
  featured,
  live_url,
  github_url,
  problem,
  solution,
  role_title,
  duration,
  year,
  tech_details,
  screenshots,
  showcase_type
) values (
  'vertex',
  'Vertex',
  'AI Search, Learning Platform, Headless CMS',
  'Grounded video-moment search for course content',
  'An AI-powered learning platform where a plain-English query returns ranked cards that deep-link to the exact second in a lesson video where the topic is taught. Built as a watch-and-build-along of the JavaScript Mastery tutorial "Build and Deploy a Full Stack Learning Platform | Search Any Video, Jump to the Exact Second", then extended past the tutorial scope.',
  'side',
  'live',
  '["AI Search", "Sanity", "Sanity Context MCP", "Next.js 16", "React 19", "TypeScript", "Clerk", "PostHog", "Vercel AI SDK", "Tailwind CSS", "PWA", "Tutorial Build-Along"]'::jsonb,
  'Tutorial build-along',
  true,
  'https://vertex-lms-app.vercel.app',
  'https://github.com/ajibolagenius/vertex-lms',
  'Course video is a black box. A learner who wants one specific idea — how caching works in server components — has to guess which lesson holds it, then scrub a 25-minute video to find the moment. Keyword search over lesson titles misses it entirely, and a chatbot answering from the model''s own memory happily invents courses, lessons and timestamps that do not exist.',
  'Credit: this project is a watch-and-build-along of the JavaScript Mastery (@javascriptmastery) tutorial "Build and Deploy a Full Stack Learning Platform | Search Any Video, Jump to the Exact Second" (published 21 August 2026) — https://www.youtube.com/watch?v=8DfvwZ812dM. The tutorial''s premise: "Stop prompting until it works. This is how you actually engineer with AI" — the AI plans first, asks for approval, and ships every feature through a reviewed pull request, driven by agent skills, context files and an AGENTS.md. I followed it end to end, then kept building. Search is the Sanity Context MCP plus an LLM writing GROQ over the deployed schema, surfaced as ranked result cards rather than a chatbox, and grounded so nothing is shown that the dataset did not return. An offline ingestion pipeline splits each video into timestamped transcript chunks and chapter markers; timestamps resolve chapters first and fall back to transcript text, and a result deep-links to the lesson page with a ?t= start second that the provider embed honours, so playback never leaves the site. Beyond the tutorial I added the "Signal" design system with zero-flash light/dark themes, an interactive in-lesson transcript panel, an "Ask this lesson" grounded Q&A with verified citation timestamps, offline-generated quizzes with streak tracking, author-curated collections and learning paths, learner progress and playback resume, PostHog engagement analytics, and an installable PWA with an offline shell. Private dataset, server-only Sanity read and write tokens, Clerk middleware gating, and no token or content write ever reaching the browser.',
  'Build-along learner & implementing engineer',
  '1 week',
  '2026',
  '[{"name":"Next.js"},{"name":"React"},{"name":"TypeScript"},{"name":"Sanity"},{"name":"GROQ"},{"name":"Sanity Context MCP"},{"name":"Vercel AI SDK"},{"name":"OpenAI"},{"name":"Clerk"},{"name":"PostHog"},{"name":"Tailwind CSS"},{"name":"Portable Text"},{"name":"Zod"}]'::jsonb,
  '[
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/4093f3fc-8652-4b4a-b4f5-54f5ba4e7227.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/28f7b052-1b9b-4ac0-9449-5bac28b82dbf.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/076a2a89-07c0-4844-804e-260db892eefb.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/df29323b-6d5e-4779-b77e-b74ca7fd1881.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/de6f5d24-b74b-42ad-8165-e49b76a97f48.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/a678fda4-caef-472c-9cc8-1281870b5f7a.webp"
  ]'::jsonb,
  null
) on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  label = excluded.label,
  description = excluded.description,
  kind = excluded.kind,
  status = excluded.status,
  tags = excluded.tags,
  type = excluded.type,
  featured = excluded.featured,
  live_url = excluded.live_url,
  github_url = excluded.github_url,
  problem = excluded.problem,
  solution = excluded.solution,
  role_title = excluded.role_title,
  duration = excluded.duration,
  year = excluded.year,
  tech_details = excluded.tech_details,
  screenshots = excluded.screenshots,
  showcase_type = excluded.showcase_type;
