-- Insert AfroGraph side project entry into public.projects
insert into public.projects (
  slug,
  name,
  category,
  label,
  description,
  kind,
  status,
  tags,
  type,
  featured,
  live_url,
  github_url,
  problem,
  solution,
  role_title,
  duration,
  year,
  tech_details,
  screenshots,
  showcase_type
) values (
  'afrograph',
  'AfroGraph',
  'Graph Database, Interactive Knowledge Graph, Music Analytics',
  'Afrobeats Cultural & Collaboration Knowledge Graph',
  'An interactive knowledge graph exploring the talent incubators (YBNL, Mavin, Starboy), sound architect producers, and multi-generational sample lineages powering the global Afrobeats phenomenon.',
  'side',
  'live',
  '["Graph Database", "CognoDB", "openCypher", "Next.js 16", "TypeScript", "D3.js", "Tailwind CSS", "neo4j-driver", "Afrobeats"]'::jsonb,
  'dev',
  true,
  'https://afrograph.vercel.app',
  'https://github.com/ajibolagenius/afrograph',
  'Music ecosystems and cultural lineages are deeply interconnected networks. Relational databases struggle with variable-depth graph traversals, talent incubation blast radii, and recursive sample ancestry without expensive multi-table joins and slow recursive CTEs.',
  'Engineered a high-performance interactive graph application powered by CognoDB Cloud (openCypher over Bolt protocol via neo4j-driver) and Next.js / D3.js. Features include shortest-path separation discovery, label talent incubation blast radius trees, multi-generational sample heritage explorer, producer hub centrality analytics, an interactive Cypher Query Studio with SQL benchmarks, and defensive Cypher security controls.',
  'Creator & Full-Stack Graph Engineer',
  '1 week',
  '2026',
  '[{"name":"CognoDB"},{"name":"openCypher"},{"name":"Next.js"},{"name":"React"},{"name":"TypeScript"},{"name":"D3.js"},{"name":"Tailwind CSS"},{"name":"neo4j-driver"}]'::jsonb,
  '[
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/bee7b425-1095-4027-85e3-50616db2f976.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/ec79e67a-3f53-4f4e-9566-b2c662bffa23.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/7d75b74a-cbbb-4b89-92be-a82204d4bb91.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/ddbb76fd-feb6-4e0a-a4c4-6e7ec22ccde1.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/ec6e2269-993d-4e92-96da-54bd95d63c09.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/cefb7222-d614-44cb-9feb-290b3dda0951.webp",
    "https://peincqeqcufbkoccyneo.supabase.co/storage/v1/object/public/project-screenshots/dc22363d-d209-40c4-8763-3802951648bc.webp"
  ]'::jsonb,
  null
) on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  label = excluded.label,
  description = excluded.description,
  kind = excluded.kind,
  status = excluded.status,
  tags = excluded.tags,
  type = excluded.type,
  featured = excluded.featured,
  live_url = excluded.live_url,
  github_url = excluded.github_url,
  problem = excluded.problem,
  solution = excluded.solution,
  role_title = excluded.role_title,
  duration = excluded.duration,
  year = excluded.year,
  tech_details = excluded.tech_details,
  screenshots = excluded.screenshots,
  showcase_type = excluded.showcase_type;
